### ISSUE TITLE
Criar a análise para o documento Entrevista.md

### ISSUE THREAD

**Issue by lukasdsouza** [Projetos-de-Extensao/PBE_24.2_8002_II_Pandora#9]
1. Você costumava usar quantas vzs o app num mês e com qual finalidade ?
2. Como funcionava esse app ?
3. Você já usou algum app por conta de uma funcionalidade que outro spp nao tinha?, se sim, qual? 
4. Teve algum problema nesse app?
5. O que você acha de uma aplicação..... ?
6. Para você qual seria o o app ideal?
7. Você gostaria de poder se cadastrar para receber novidade no desenvolvimento de um app que englobe tudo que há de mias importnte para você? 
8. Você gostaria que as informações chegassem até você por meio de onde?

**Comment by jonh-carvalho** [comment]
1. Todos os dias - um dia de descanso
2. Funcionava recebendo informações do relógio para as atividades de natação, corrida e ciclismo
3. O App mais completo é do fabricante do relógio mas os recursos de redes sociais são limitados, fazendo parte de uma assessoria é interessante a visualização de todos os membros como forma de motivação.
4. Em geral o problema desses apps são em relação as informações do gps.
5. O foco de uma aplicação para um grupo específico ou esporte específico deveria ser estreitar as relações com os membros.
6. Mesma resposta acima
7. Sim
8. Email
